name: Docker Application CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    uses: anujdevopslearn/GithubActionsWorkflows/.github/workflows/maven.yml@main
    with:
      build-script: pom.xml
  docker-build:
    needs: build
    uses: anujdevopslearn/GithubActionsWorkflows/.github/workflows/docker.yml@main
    with:
      image_name: anuj-image
    secrets: 
        docker_user: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
