name: Docker Application CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    uses: anujdevopslearn/GithubActionsWorkflows/.github/workflows/maven.yml@main
    with:
      build-script: pom.xml
